services:
  redis-base:
    image: ghcr.io/lukastrkan/redis8
    volumes:      
      - ./config/redis.conf:/redis.conf:ro
      - ./certs:/certs:ro
      - ./config/access-rights.acl:/access-rights.acl:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "--tls", "--cert", "/certs/redis.crt", "--key", "/certs/redis.key","--cacert", "/certs/ca.crt", "-a", "strongpassword", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s