name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-redis-stack-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push redis'
        run: |
          docker build . -f Dockerfile -t ghcr.io/lukastrkan/redis-server-oss:latest
          docker push ghcr.io/lukastrkan/redis-server-oss:latest

  push-redis-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push rcproxy'
        run: |
          docker build . -f redis.Dockerfile -t ghcr.io/lukastrkan/redis8:latest
          docker push ghcr.io/lukastrkan/redis8:latest

  push-rcproxy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push rcproxy'
        run: |
          docker build . -f rcproxy.Dockerfile -t ghcr.io/lukastrkan/rcproxy:latest
          docker push ghcr.io/lukastrkan/rcproxy:latest
