name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-redis-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build redis'
            run: |
              docker build . -f Dockerfile --tag ghcr.io/lukastrkan/redis-server-oss:latest
              docker push ghcr.io/lukastrkan/redis-server-oss:latest
          - name: 'Build rcproxy' 
            run: |
              docker build . -f rcproxy.Dockerfile --tag ghcr.io/lukastrkan/rcproxy:latest
              docker push ghcr.io/lukastrkan/rcproxy:latest
